server:
  port: 8081
spring:
  application:
    name: consumer-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka,http://eureka2:8762/eureka
  #指定eureka的网页里显示本机网址
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
