package cn.itcast.logistics.common

/**
 * 定义表名：根据表的名字定义属性
 */
object TableMapping {
	
	val EMP_INFO_MAP: String = "tbl_emp_info_map"
	val DRIVER: String = "tbl_driver"
	val EMP: String = "tbl_emp"
	val WAREHOUSE_TRANSPORT_TOOL: String = "tbl_warehouse_transport_tool"
	val CHARGE_STANDARD: String = "tbl_charge_standard"
	val COMPANY: String = "tbl_company"
	val COMPANY_DOT_MAP: String = "tbl_company_dot_map"
	val COMPANY_TRANSPORT_ROUTE_MA: String = "tbl_company_transport_route_ma"
	val COMPANY_WAREHOUSE_MAP: String = "tbl_company_warehouse_map"
	val COURIER: String = "tbl_courier"
	val DELIVER_REGION: String = "tbl_deliver_region"
	val DELIVERY_RECORD: String = "tbl_delivery_record"
	val DEPARTMENT: String = "tbl_department"
	val FIXED_AREA: String = "tbl_fixed_area"
	val GOODS_RACK: String = "tbl_goods_rack"
	val JOB: String = "tbl_job"
	val OUT_WAREHOUSE_DETAIL: String = "tbl_out_warehouse_detail"
	val PKG: String = "tbl_pkg"
	val POSTAL_STANDARD: String = "tbl_postal_standard"
	val PUSH_WAREHOUSE_DETAIL: String = "tbl_push_warehouse_detail"
	val SERVICE_EVALUATION: String = "tbl_service_evaluation"
	val STORE_GRID: String = "tbl_store_grid"
	val VEHICLE_MONITOR: String = "tbl_vehicle_monitor"
	val WAREHOUSE_RACK_MAP: String = "tbl_warehouse_rack_map"
	val WAREHOUSE_RECEIPT_DETAIL: String = "tbl_warehouse_receipt_detail"
	val WAYBILL_LINE: String = "tbl_waybill_line"
	val WAYBILL_STATE_RECORD: String = "tbl_waybill_state_record"
	val WORK_TIME: String = "tbl_work_time"
	val AREAS: String = "tbl_areas"
	val DELIVER_PACKAGE: String = "tbl_deliver_package"
	val CUSTOMER: String = "tbl_customer"
	val CODES: String = "tbl_codes"
	val WAREHOUSE: String = "tbl_warehouse"
	val CONSUMER_ADDRESS_MAP: String = "tbl_consumer_address_map"
	val WAREHOUSE_RECEIPT: String = "tbl_warehouse_receipt"
	val WAREHOUSE_SEND_VEHICLE: String = "tbl_warehouse_send_vehicle"
	val WAREHOUSE_VEHICLE_MAP: String = "tbl_warehouse_vehicle_map"
	val DOT: String = "tbl_dot"
	val TRANSPORT_TOOL: String = "tbl_transport_tool"
	val DOT_TRANSPORT_TOOL: String = "tbl_dot_transport_tool"
	val ADDRESS: String = "tbl_address"
	val ROUTE: String = "tbl_route"
	val PUSH_WAREHOUSE: String = "tbl_push_warehouse"
	val OUT_WAREHOUSE: String = "tbl_out_warehouse"
	val WAREHOUSE_EMP: String = "tbl_warehouse_emp"
	val EXPRESS_PACKAGE: String = "tbl_express_package"
	val EXPRESS_BILL: String = "tbl_express_bill"
	val CONSUMER_SENDER_INFO: String = "tbl_consumer_sender_info"
	val COLLECT_PACKAGE: String = "tbl_collect_package"
	val WAY_BILL: String = "tbl_waybill"
	val TRANSPORT_RECORD: String = "tbl_transport_record"
	
}

